### ISSUE TITLE
Strange Output Data

### ISSUE THREAD

**Issue by OliverW1986** [TheHolyCows/cowlibration-field#1]
After some fidgeting with the code and build process (this is my first time trying to run a C++ program) I was able to get it to run using Visual Studio's Local Windows Debugger. It then processed all of the video frames, but it had an error after processing. 
WARNING: Logging before InitGoogleLogging() is written to STDERR
E20240605 10:58:59.803719 31608 solver.cc:508] Terminating: Can't use SPARSE_NORMAL_CHOLESKY with Solver::Options::sparse_linear_algebra_library_type = NO_SPARSE.
Ceres Solver Report: Iterations: -2, Initial cost: -1.000000e+00, Final cost: -1.000000e+00, Termination: FAILURE
I decided to dismiss this and check if it had worked. It did output a field map, however, tags 6-10 were all on top of each other, and the only tag that I could see in the visualizer was tag 7 (most likely 6-10 though).
[2024-champs-blue.json](https://github.com/user-attachments/files/15593410/2024-champs-blue.json)
Here is my output field map file. I can also send my build files if that would help.

**Comment by bellfrog1** [comment]
We replicated the problem using the provided example data and we had the same problem.

**Comment by dustinlieu** [comment]
@ImpactTang @bellfrog1 This should be fixed by PR #2. Can you try pulling the latest changes, rebuilding, and running the calibration tool again?
